apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demoapp1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abdulk3/argo.git
    targetRevision: HEAD
    path: argo_demo/demoapp/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: demoapp
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
